project_id = "bmcpznzahqahiujyfkuj"

[functions.delete-account]
verify_jwt = false

[functions.verify-email-exists]
verify_jwt = false

[functions.check-email]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

